// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TemperaturaBack.Data.Entities;

public partial class TemperaturaDbContext : DbContext
{
    public TemperaturaDbContext(DbContextOptions<TemperaturaDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Temperatura> Temperaturas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Temperatura>(entity =>
        {
            entity.HasKey(e => e.IoT);

            entity.Property(e => e.FechaHora).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}