// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Practica04.Data.Models;

public partial class TDetallesPresupuesto
{
    public int IdDetalle { get; set; }

    public int IdPresupuesto { get; set; }

    public int IdProducto { get; set; }

    public int Cantidad { get; set; }

    public double Precio { get; set; }

    public virtual TPresupuesto IdPresupuestoNavigation { get; set; }

    public virtual TProducto IdProductoNavigation { get; set; }
}