// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Practica04.Data.Models;

public partial class TProducto
{
    public int Codigo { get; set; }

    public string NProducto { get; set; }

    public int Stock { get; set; }

    public bool EstaActivo { get; set; }

    public virtual ICollection<TDetallesPresupuesto> TDetallesPresupuestos { get; set; } = new List<TDetallesPresupuesto>();
}