// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackRecetas.Data.Entities;

public partial class Ingrediente
{
    public int IdIngrediente { get; set; }

    public string NIngrediente { get; set; }

    public double Cantidad { get; set; }

    public int IdReceta { get; set; }

    public virtual Receta IdRecetaNavigation { get; set; }
}