// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BackRecetas.Data.Entities;

public partial class Receta
{
    public int IdReceta { get; set; }

    public string Nombre { get; set; }

    public string Cheff { get; set; }

    [JsonIgnore]
    public virtual ICollection<Ingrediente> Ingredientes { get; set; } = new List<Ingrediente>();
}