// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductoBack.Data.Models;

public partial class Producto
{
    public int Codigo { get; set; }

    public string Nombre { get; set; }

    public float Precio { get; set; }

    public DateTime? FechaBaja { get; set; }

    public string MotivoBaja { get; set; }
}