// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Negocio.Data.Entities;

public partial class TTurno
{
    public int Id { get; set; }

    public string Fecha { get; set; }

    public string Hora { get; set; }

    public string Cliente { get; set; }

    public DateTime? FechaCancelacion { get; set; }

    public string MotivoCancelacion { get; set; }

    public virtual ICollection<TDetallesTurno> TDetallesTurnos { get; set; } = new List<TDetallesTurno>();
    public TTurno()
    {
        Fecha = DateTime.Now.AddDays(1).ToString();
    }
}