// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineBack.Data.Entities;

public partial class Pelicula
{
    public int Id { get; set; }

    public string Titulo { get; set; }

    public string Director { get; set; }

    public int Anho { get; set; }

    public int Genero { get; set; }

    public bool? Estreno { get; set; }

    public virtual Genero GeneroNavigation { get; set; }
}